version: 1
disable_existing_loggers: false

formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: logs/devops-tools.log
    maxBytes: 10485760  # 10MB
    backupCount: 5

loggers:
  devops_tools:
    level: DEBUG
    handlers: [console, file]
    propagate: false

  devops_tools.aws:
    level: INFO
    handlers: [console, file]
    propagate: false

  devops_tools.containers:
    level: INFO
    handlers: [console, file]
    propagate: false

root:
  level: WARNING
  handlers: [console]
